### ISSUE TITLE
GPL-3.0 License Question, Do my NFTs and Dapps Accessing Them Have to Be Open Source?

### ISSUE THREAD

**Issue by ChristianOConnor** [baedrik/snip721-reference-impl#9]
Hey I just realized that this project is GPL-3 licensed. Does that mean that any NFT I implement with this repo has to have the same license? Like if I made a cool 3D art file that was in any way code generated, would I have to release the source code? Also, I use a svelte frontend for an NFT minting dapp similar to the code in this repo https://github.com/floAr/FigmentLearn-FromZeroToYourFirstSecretNFT. Does that mean I have to make my whole dapp open source because I used https://github.com/baedrik/snip721-reference-impl to make the actual NFTs?

**Comment by baedrik** [comment]
Just copy-pasting my discord reply to the same question:
I honestly don't know the legal nuances of gpl3, and it is mostly there because when I was copying files/folder structure as a starting point, the repo I was using as a "template" had that license.  That said, I did feel that if it meant that if anyone made improvements or additions to the reference implementation, that it should be open sourced for the entire sNFT ecosystem to benefit from, I'd be good with that.  I'm under the impression that you do not need to open source pieces that you write that will interact with it because you will not be distributing it, but rather running that code on your own webservers and providing a service instead of distributing it.  Honestly, the fact that the SecretNetwork and toolkit code is AGPL3, might mean that all secret contracts have to be open source since they are including AGPL3 stuff as dependencies, but I really don't know

**Comment by ChristianOConnor** [comment]
> Just copy-pasting my discord reply to the same question: I honestly don't know the legal nuances of gpl3, and it is mostly there because when I was copying files/folder structure as a starting point, the repo I was using as a "template" had that license. That said, I did feel that if it meant that if anyone made improvements or additions to the reference implementation, that it should be open sourced for the entire sNFT ecosystem to benefit from, I'd be good with that. I'm under the impression that you do not need to open source pieces that you write that will interact with it because you will not be distributing it, but rather running that code on your own webservers and providing a service instead of distributing it. Honestly, the fact that the SecretNetwork and toolkit code is AGPL3, might mean that all secret contracts have to be open source since they are including AGPL3 stuff as dependencies, but I really don't know

Thanks! This is a good answer and I appreciate the feedback.
